filebeat.inputs:
- type: log  
  paths:
    - /home/sync-data/default/*.log
  # multiline:
  #     pattern: ^\d{4}
  #     negate: true
  #     match: after
  fields:
    doc_type: sync-data.default
- type: log     
  paths:
    - /home/sync-data/sql/*.log
  # multiline:
  #     pattern: ^\d{4}
  #     negate: true
  #     match: after
  fields:
    doc_type: sync-data.sql
output.logstash: # 输出地址
  hosts: ["192.168.109.100:5044"]  
