FROM php:8.0-fpm-alpine3.12

COPY ./lib/composer.phar /tmp/composer.phar
COPY ./lib/redis-5.3.4.tgz /tmp/redis-5.3.4.tgz
COPY ./lib/swoole-4.7.1.tgz /tmp/swoole-4.7.1.tgz
COPY ./lib/amqp-1.11.0beta.tgz /tmp/amqp-1.11.0beta.tgz
COPY ./lib/rabbitmq-c-0.9.0-master.tar.gz /tmp/rabbitmq-c-0.9.0-master.tar.gz
COPY ./lib/mongodb-1.11.0alpha1.tgz /tmp/mongodb-1.11.0alpha1.tgz

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add git wget openssl openssl-dev libstdc++ cmake build-base \
    && cd /tmp \
    && tar -zxvf redis-5.3.4.tgz \
    && tar -zxvf swoole-4.7.1.tgz \
    && tar -zxvf amqp-1.11.0beta.tgz \
    && tar -zxvf rabbitmq-c-0.9.0-master.tar.gz \
	&& tar -zxvf mongodb-1.11.0alpha1.tgz \
    && cd rabbitmq-c-0.9.0-master \
    && mkdir build \
    && cd build \
    && cmake .. \
    && cd .. \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/rabbitmq-c \
    && cmake --build . --target install \
    && mv /usr/local/rabbitmq-c/lib64 /usr/local/rabbitmq-c/lib \
    && cd .. \
    && docker-php-source extract \
    && mv redis-5.3.4 /usr/src/php/ext/redis \
    && mv swoole-4.7.1 /usr/src/php/ext/swoole \
    && mv amqp-1.11.0beta /usr/src/php/ext/amqp \
	&& mv mongodb-1.11.0alpha1 /usr/src/php/ext/mongodb \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    && docker-php-ext-configure swoole --enable-openssl --enable-http2 \
    && docker-php-ext-configure amqp --with-librabbitmq-dir=/usr/local/rabbitmq-c \
    && docker-php-ext-install bcmath sockets pcntl redis swoole pdo_mysql amqp mongodb \
    && mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && rm -rf redis-5.3.4.tgz swoole-4.7.1.tgz amqp-1.11.0beta.tgz rabbitmq-c-0.9.0-master.tar.gz rabbitmq-c-0.9.0-master mongodb-1.11.0alpha1.tgz \
    && docker-php-source delete \
    && mkdir /www


WORKDIR /www

EXPOSE 4000