version: "3.6"

services: 
    php74:
        image: php74
        build: ./php74
        container_name: php74
        networks: 
            wfw:
                ipv4_address: 172.22.22.160
        ports:
        - "6816:6816"
        - "6850:6850"
        - "6868:6868"
        - "6869:6869"
        - "6604:6604"
        - "6603:6603"
        volumes:
        - "/etc/localtime:/etc/localtime"
        - "./php74/php.ini:/usr/local/etc/php/php.ini"
        - "./php74/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        - "./php74/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
        - "/mnt/hgfs/www:/www"
        privileged: true
        restart: always             
    rabbitmq-node1:
        image: rabbitmq:3.8-management-alpine
        container_name: rabbitmq-node1
        networks: 
            wfw:
                ipv4_address: 172.22.22.150
        ports: 
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "/etc/localtime:/etc/localtime"
            - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
            - "./rabbitmq/data:/var/lib/rabbitmq" 
        hostname: node1  
        privileged: true
        restart: always 
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        networks: 
            wfw:
                ipv4_address: 172.22.22.155
        ports:
            - 2182:2181
            - 2888:2888
            - 3888:3888
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
        volumes:
            - ./zookeeper/data:/data
            - ./zookeeper/datalog:/datalog
        restart: always
    kafka:
        image: wurstmeister/kafka:2.13-2.7.0
        container_name: kafka
        networks: 
            wfw:
                ipv4_address: 172.22.22.165
        ports:
        - "9092:9092"
        - "1099:1099"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 192.168.229.100 ## 修改:宿主机IP
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.229.100:9092
            KAFKA_ZOOKEEPER_CONNECT: "192.168.229.100:2182"
            KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.229.100 -Dcom.sun.management.jmxremote.rmi.port=1099"
            JMX_PORT: 1099
        volumes:
        - "./kafka/data/:/kafka"
        restart: always
    kafka-manager:
        image: kafkamanager/kafka-manager
        container_name: kafka-manager
        hostname: kafka-manager
        ports:
        - "9002:9000"
        depends_on:
        - "kafka"
        environment:
            ZK_HOSTS: 192.168.229.100:2182
            TZ: CST-8
        restart: always
    mongo-db:
        image: mongo:latest
        container_name: mongo-db
        networks:
            wfw:
                ipv4_address: 172.22.22.170
        ports:
        - "27017:27017"
        privileged: true
        restart: always
    redis-db:
        image: redis:latest
        container_name: redis-db
        networks:
            wfw:
                ipv4_address: 172.22.22.180
        ports:
        - "6379:6379"
        hostname: redis01
        privileged: true
        restart: always
networks:
    wfw:
        name: "docker_wfw"
        driver: "bridge"
        ipam:
            config:
            - subnet: 172.22.22.0/24


