version: "3.6"

services: 
    rabbitmq-node1:
        image: rabbitmq:3.8-management-alpine
        container_name: rabbitmq-node1
        networks: 
            wfw:
                ipv4_address: 172.22.22.150
        ports: 
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
            - "./rabbitmq/data:/var/lib/rabbitmq" 
        hostname: node1  
        privileged: true
        restart: always              

networks: 
    wfw:
        driver: "bridge"
        ipam: 
            config: 
                - subnet: 172.22.22.0/24


