#author Tina.Lee
FROM elasticsearch:7.14.0
#es插件目录
# # lib目录的zip文件，拷贝至elasticsearch的插件目录
# RUN yum install wget unzip  \
#     && cd /usr/share/elasticsearch/plugins  \
#     && mkdir ik \
#     && cd ik \
#     && wget https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.13.4/elasticsearch-analysis-ik-7.14.0.zip \
#     && unzip elasticsearch-analysis-ik-7.13.4.zip \
#
#
# EXPOSE 9200
#RUN cd /usr/share/elasticsearch && ./bin/elasticsearch-plugin install --patch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.13.4/elasticsearch-analysis-ik-7.13.4.zip

# docker build elasticsearch/
COPY ./plugins/ik/ /usr/share/elasticsearch/plugins/ik/: