version: "3.6"

services: 
    postgres:
        image: postgres:9.6
        container_name: postgres
        networks: 
            wfw:
                ipv4_address: 172.22.22.120
        ports: 
            - "5432:5432"        
        environment: 
            POSTGRES_PASSWORD: "postgres"
        volumes: 
            - "./postgres/data:/var/lib/postgresql/data"
            - "./postgres/postgresql.conf:/etc/postgresql/postgresql.conf" 
            - "./postgres/init_user_db.sh:/docker-entrypoint-initdb.d/init_user_db.sh"       
        restart: always   
    # docker run --rm \
    # --network=docker_wfw \
    # -e "KONG_DATABASE=postgres" \
    # -e "KONG_PG_HOST=postgres" \
    # -e "KONG_PG_PASSWORD=123123" \
    # -e "KONG_CASSANDRA_CONTACT_POINTS=postgres" \
    # kong:2.1.4 kong migrations bootstrap    
    kong:
        image: kong:2.1.4
        container_name: kong
        networks: 
            wfw:
                ipv4_address: 172.22.22.121
        ports: 
            - "8000:8000"          
            - "8001:8001"          
            - "8443:8443"          
            - "8444:8444"          
        environment: 
            KONG_DATABASE: "postgres"
            KONG_PG_HOST: "172.22.22.120"
            KONG_PG_PASSWORD: 123123
            KONG_CASSANDRA_CONTACT_POINTS: "postgres"
            KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        privileged: true
        restart: always
    # docker run --rm \
    # --network docker_wfw \
    # pantsel/konga \
    # -c prepare \
    # -a postgres \
    # -u postgresql://konga:123123@postgres:5432/konga    
    konga:
        image: pantsel/konga
        container_name: konga
        networks: 
            wfw:
                ipv4_address: 172.22.22.122
        volumes: 
            - "./konga/lib/assets:/app/assets"
        ports: 
            - "1337:1337"          
        environment: 
            TOKEN_SECRET: "yyb-konga"
            DB_ADAPTER: "postgres"   
            DB_HOST: "172.22.22.120"
            DB_PORT: 5432
            DB_USER: "konga" 
            DB_PASSWORD: "123123"
            DB_DATABASE: "konga" 
            NODE_ENV: "production"   
        privileged: true
        restart: always               

networks: 
    wfw:
        name: "docker_wfw"
        external: true


